import 'package:flutter/material.dart';

// Глобальна змінна, яка сповіщає систему про зміну мови
final ValueNotifier<Locale> appLocale = ValueNotifier(const Locale('uk'));

class S {
  static final Map<String, Map<String, String>> _values = {
    'uk': {
      "create_file": "Створити файл",
      "file_name": "Назва файлу",
      "format": "Формат (напр. txt)",
      "cancel": "Скасувати",
      "create": "Створити",
      "save": "Зберегти",
      "delete_file": "Видалити файл (назавжди)",
      "remove_from_folder": "Прибрати з папки",
      "add_tag": "Додати тег",
      "open": "Відкрити",
      "delete_arrow": "Видалити стрілку",
      "access_denied": "Доступ заборонено",
      "login_required_hosting":
          "Для створення хостинг-дошок потрібно увійти в акаунт.",
      "ok": "OK",
      "notes": "Нотатки",
      "enter_note_hint": "Введіть текст нотатки тут...",
      "tags_for": "Теги для",
      "enter_new_tag": "Новий тег",
      "existing_tags": "Існуючі теги",
      "drop_files": "Перетягніть файли сюди",
      "upload_file": "Завантажити файл",
      "files_list": "Список файлів",
      "tags": "Теги",
      "folders": "Папки",
      "users": "Учасники",
      "search_hint": "Пошук",
      "arrow_mode_hint":
          "Режим стрілок (клік для малювання, ПКМ для налаштувань)",
      // Головне меню
      'my_boards': 'Мої дошки',
      'hosting': 'Хостинг',
      'joined': 'Приєднані',
      'boards': 'дошок',
      'weight': 'Вага',
      'sent': 'Надіслано',
      'received': 'Прийнято',
      'select_dir': 'Обрати робочу директорію',
      'change_dir': 'Змінити директорію',
      'policy': 'Умови використання та Політика',
      'profile': 'Профіль',
      'login': 'Вхід',
      'registration': 'Реєстрація',
      'auth_reg': 'Реєстрація',
      'auth_login': 'Вхід',
      'login_hint': 'Увійти/Зареєструватися',

      // Нові кнопки та Шаринг (Share/Connect)
      'share': 'Поділитися',
      'connect': 'Підключитися',
      'share_board_title': 'Поділитися дошкою',
      'copy_id': 'Скопіювати ID',
      'share_instruction':
          'Надішліть цей ID іншим користувачам, щоб вони могли приєднатися до вашої сесії. Для підключення їм потрібно ввести цей код у розділі "Приєднані".',
      'board_id': 'ID Дошки',
      'share_id': 'Поділитися ID',

      // Повідомлення та помилки (Start Screen)
      'dir_set': 'Робоча папка встановлена:',
      'name_changed': 'Ім’я змінено!',
      'special_thanks': 'Особлива подяка',
      'thanks_desc':
          'Цей проект став можливим завдяки допомозі цих чудових людей:',
      'open_profile': 'Відкрити профіль',
      'link_error': 'Не вдалося відкрити посилання',
      'board_deleted_success': 'Дошку успішно видалено',
      'delete_error': 'Помилка видалення дошки',
      'dir_error': 'Помилка: Робоча папка не налаштована.',
      'id_copied': 'ID скопійовано!',
      'welcome_user': 'Вітаємо,',
      'logout_confirm': 'Ви вийшли з акаунту',

      // Профіль та Авторизація
      'unknown': 'Невідомо',
      'username': 'Ім\'я користувача',
      'public_id_hint': 'Public ID ',
      'change_password': 'Змінити пароль',
      'logout': 'Вийти з акаунту',
      'reset_password': 'Відновлення пароля',
      'your_email': 'Ваш Email',
      'email_code': 'Код з пошти',
      'new_password': 'Новий пароль',
      'cancel': 'Скасувати',
      'save': 'Зберегти',
      'close': 'Закрити',
      'enter_email': 'Введіть email',
      'update_pass': 'Оновити пароль',
      'get_code': 'Отримати код',
      'forgot_password': 'Забули пароль?',
      'confirm_pass': 'Підтвердження',
      'min_6_chars': 'Мін. 6 символів',
      'pass_mismatch': 'Паролі не співпадають',
      'finish_reg': 'Завершити реєстрацію',
      'code_sent_email': 'Код підтвердження відправлено на email',
      'change_name': 'Змінити ім\'я',
      'enter_new_name': 'Введіть нове ім\'я',
      'request_error': 'Помилка запиту',
      'password_changed_success': 'Пароль успішно змінено!',
      'reset_error': 'Помилка скидання',
      'unknown_error': 'Невідома помилка',
      'network_error': 'Помилка мережі:',
      'reg_success': 'Реєстрація пройшла успішно',
      'reg_error': 'Помилка реєстрації:',
      'email': 'Електронна пошта',
      'invalid_email': 'Некоректний email',
      'password': 'Пароль',
      'confirm_code': 'Код підтвердження',
      '6_digits': '6 цифр',
      'login_btn': 'Увійти',
      'confirm': 'Підтвердити',
      'data_fetch_error': 'Помилка отримання даних:',
      'error_prefix': 'Помилка:',

      // Екран дошки (Canvas/Board)
      'new_folder': 'Нова папка',
      'create_folder': 'Створити папку',
      'folder_name': 'Назва папки',
      'pick_color': 'Оберіть колір:',
      'add_to_folder': 'Додати до папки:',
      'objects': 'об\'єктів',
      'files_count': 'файл(ів)',
      'create_file': 'Створити файл',
      'file_name': 'Назва файлу',
      'format': 'Формат',
      'new_file_default': 'Новий файл',
      'create_file_error': 'Помилка створення файлу:',
      'blocked_ids': 'Заблоковані ID',
      'blacklist_empty': 'Чорний список порожній',
      'unblock': 'Розблокувати',
      'file_exists': 'Файл вже існує',
      'add_again_q': 'вже доданий на дошку. Додати знову?',
      'pick_files_error': 'Не вдалося вибрати файли:',
      'open': 'Відкрити',
      'remove_from_folder': 'Прибрати з папки',
      'add_tag': 'Додати тег',
      'remove_from_board': 'Прибрати з дошки',
      'delete_file': 'Видалити файл',
      'tags_for': 'Тег(и) для',
      'enter_new_tag': 'Введіть новий тег',
      'existing_tags': 'Існуючі теги:',
      'notes': 'Нотатки',
      'enter_note_hint': 'Введіть нотатку...',
      'delete_arrow': 'Видалити стрілку',
      'arrow_settings': 'Налаштування стрілки',
      'line_width': 'Товщина лінії:',
      'color': 'Колір:',
      'preview': 'Попередній перегляд:',
      'files_list': 'Список файлів',
      'tags': 'Теги',
      'folders': 'Папки',
      'users': 'Учасники',
      'arrow_mode_hint': 'ЛКМ: Режим стрілок | ПКМ: Налаштування',
      'upload_file': 'Завантажити файл',
      'search_hint': 'Пошук',
      'no_files_found': 'Файлів не знайдено',
      'no_tags_found': 'Тегів не знайдено',
      'no_folders_found': 'Папок не знайдено',
      'no_active_users': 'Активних учасників немає',
      'blacklist': 'Чорний список',
      'disconnect': 'Відключити',
      'block': 'Заблокувати',
      'management': 'Керування',
      'drop_files': 'Перетягніть файли сюди',
      'file_not_found': 'Файл не знайдено:',
      'open_error': 'Помилка відкриття:',

      // Спільні діалоги
      'delete_q': 'Видалити?',
      'delete_board_q': 'Видалити дошку?',
      'no': 'Ні',
      'yes': 'Так',
      'board_deleted': 'Дошку видалено',
      'create': 'Створити',
      'no_boards': 'Немає дошок',
      'load_error': 'Не вдалося завантажити',
      'title_for_self': 'Назва (для себе)',
      'board_id': 'ID Дошки',
      'join': 'Приєднатися',
      'add': 'Додати',
      'delete_from_list_q': 'Видалити зі списку?',
      'no_joined_boards': 'Немає приєднаних дошок',
      'guest': 'Гість',
      'no_local_boards': 'Немає локальних дошок',
      'create_new_board': 'Створити нову дошку',
      'board_name_hint': 'Напр. "Мій Проект"',
      'board_name': 'Назва дошки',
      'create_board_error': 'Помилка створення дошки:',
      'board_removed': 'Дошку видалено',
      'new_board': 'Нова дошка',
      'no_boards_for_hosting': 'Немає дошок для хостингу',
      // Політика
      'policy_title': 'Умови та Політика',
      'decline': 'Відмовитись',
      'agree': 'Я погоджуюсь',
      'loading': 'Завантаження...',
      'policy_load_error':
          'Помилка завантаження тексту політики. Зверніться в підтримку.',

      'arrow_settings_title': 'Налаштування стрілки',
      'arrow_thickness': 'Товщина лінії:',
      'arrow_color': 'Колір:',
      'preview_label': 'Попередній перегляд:',
      'pro_title': 'Boardly+',
      'pro_desc': 'Отримайте доступ до розширених функцій для себе та друзів.',
      'add_friend_label': 'Додати друга (Public ID):',
      'enter_id_hint': 'Введіть ID...',
      'total_accounts': 'Всього акаунтів:',
      'buy_pro': 'Купити Boardly+',
      'pro_redirect': 'Перехід до оплати...',
      'pro_active': 'Boardly+',
      'pro_active_desc': 'Всі функції розблоковано',
      'pro_badge': 'Boardly+',
      'accounts_count': 'акаунтів',

      'session_full_host':
          'Ліміт учасників досягнуто. Оформіть Boardly+ для збільшення ліміту.',

      'session_full_guest': 'Сесія переповнена. Хост досяг ліміту підключень.',

      'session_full_title': 'Доступ обмежено',

      'about_title': 'Про додаток',
      'app_description':
          'Короткий опис додатку (2-4 рядки). Наприклад: Це інструмент для спільної роботи в реальному часі, що дозволяє легко обмінюватися ідеями...',

      'features_title': 'Ключові можливості',
      'feature_1': 'Синхронізація в реальному часі',
      'feature_2': 'Підтримка різних типів файлів',
      'feature_3': 'Безпечне з\'єднання',

      'security_title': 'Безпека та Синхронізація',
      'security_desc':
          'Короткий опис того, як працює шифрування або P2P з\'єднання...',

      'team_title': 'Команда розробників',
      'developer': 'Розробник',
      'tester': 'QA / Тестування',
      'designer': 'UI/UX та Логотип',

      'contacts_title': 'Контакти та Інфо',
      'website': 'Веб-сайт',
      'feedback': 'Написати нам',

      'resources_title': 'Використані ресурси (Credits)',
      'resources_desc': 'Графіка та іконки надані авторами:',

      'app_version': 'Версія додатку',
      'build_number': 'Збірка',

      'pro_title': 'Boardly+',
      'pro_desc': 'Отримайте доступ до розширених функцій для себе та друзів.',
      'add_friend_label': 'Додати друга (Public ID):',
      'enter_id_hint': 'Введіть ID...',
      'total_accounts': 'Всього акаунтів:',
      'buy_pro': 'Купити Boardly+',
      'pro_redirect': 'Перехід до оплати...',
      'cancel': 'Скасувати',
      'username':
          'Ви', // Змінив "Ім'я користувача" на "Ви" для контексту "Ви + друзі"
      'error_prefix': 'Помилка:',
      'network_error': 'Помилка мережі:',

      'manage_subscription': 'Керувати підпискою',
      'subscription_settings': 'Налаштування плану та оплати',

      // === НОВІ КЛЮЧІ ДЛЯ PAYMENT DIALOG ===
      'choose_sub_type': 'Оберіть тип підписки:',
      'sub_single': 'Одиночна підписка',
      'sub_team': 'Командна підписка',
      'sub_gift': 'Купити друзям',
      'gift_friends': 'Подарунок друзям',
      'add_one_friend_error': 'Додайте хоча б одного друга',
      'server_error': 'Помилка сервера',
      'processing': 'Обробка запиту...',
      'link_open_error': 'Не вдалося відкрити посилання',

      // === НОВІ КЛЮЧІ ДЛЯ ЛІМІТІВ ===
      'limit_reached': 'Ліміт вичерпано',
      'limit_join_desc':
          'У безкоштовній версії можна зберегти лише 1 дошку для приєднання. Оформіть PRO для безліміту.',
      'limit_host_desc':
          'У безкоштовній версії можна створити лише 1 дошку для хостингу. Оформіть PRO для безліміту.',
      'get_boardly_plus': 'Оформити BOARDLY+',
      'unlock_features': 'Розблокуй всі можливості',

      'delete_account': 'Видалити акаунт',
      'delete_account_title': 'Видалення акаунту',
      'delete_account_confirm': 'Ви впевнені, що хочете видалити свій акаунт?',
      'delete_warning_pro': 'Увага! У вас активна підписка Boardly+.',
      'delete_desc_pro':
          'Якщо ви видалите акаунт:\n• Ви назавжди втратите підписку Boardly+.\n• Ви більше не зможете працювати в команді.\n• Всі ваші "Хостинг" дошки стануть звичайними локальними дошками у списку "Мої дошки".',
      'delete_desc_free':
          'Ця дія незворотна. Ваші дошки залишаться на пристрої, але ви втратите свій Public ID та доступ до хмарних функцій.',
      'delete_btn_confirm': 'Так, видалити назавжди',

      'tags_not_found': 'Тегів не знайдено',
      'folders_not_found': 'Папок не знайдено',
      'no_active_members': 'Активних учасників немає',
      'blacklist': 'Чорний список',
      'files': 'Файлів',

      "files_not_found": "Файлів не знайдено",
      "terms_and_policy": "Умови та Політика",
    },
    'en': {
      'files': 'Files',
      'tags_not_found': 'No tags found',
      'folders_not_found': 'No folders found',
      'no_active_members': 'No active members',
      'blacklist': 'Blacklist',
      "create_file": "Create File",
      "file_name": "File Name",
      "format": "Format (e.g. txt)",
      "cancel": "Cancel",
      "create": "Create",
      "save": "Save",
      "delete_file": "Delete File (Permanently)",
      "remove_from_folder": "Remove from Folder",
      "add_tag": "Add Tag",
      "open": "Open",
      "delete_arrow": "Delete Arrow",
      "access_denied": "Access Denied",
      "login_required_hosting":
          "You must be logged in to create hosting boards.",
      "ok": "OK",
      "notes": "Notes",
      "enter_note_hint": "Enter your note here...",
      "tags_for": "Tags for",
      "enter_new_tag": "New tag",
      "existing_tags": "Existing tags",
      "drop_files": "Drop files here",
      "upload_file": "Upload File",
      "files_list": "Files List",
      "tags": "Tags",
      "folders": "Folders",
      "users": "Participants",
      "search_hint": "Search",
      "arrow_mode_hint": "Arrow Mode (click to draw, RMB for settings)",

      'no_boards_for_hosting': 'No boards available for hosting',
      "files_not_found": "Files not found",
      "terms_and_policy": "Terms and Policy",
      'manage_subscription': 'Manage Subscription',
      'subscription_settings': 'Plan settings and payments',

      'delete_account': 'Delete Account',
      'delete_account_title': 'Delete Account',
      'delete_account_confirm': 'Are you sure you want to delete your account?',
      'delete_warning_pro':
          'Warning! You have an active Boardly+ subscription.',
      'delete_desc_pro':
          'If you delete your account:\n• You will permanently lose your Boardly+ subscription.\n• You will lose access to team collaboration.\n• All your "Hosting" boards will become regular local boards in "My Boards".',
      'delete_desc_free':
          'This action is irreversible. Your boards will remain on your device, but you will lose your Public ID and cloud features.',
      'delete_btn_confirm': 'Yes, delete forever',
      // ... (Your existing keys) ...
      'pro_title': 'Boardly+',
      'pro_desc': 'Get access to advanced features for yourself and friends.',
      'add_friend_label': 'Add friend (Public ID):',
      'enter_id_hint': 'Enter ID...',
      'total_accounts': 'Total accounts:',
      'buy_pro': 'Buy Boardly+',
      'pro_redirect': 'Redirecting to payment...',
      'cancel': 'Cancel',
      'username': 'You',
      'error_prefix': 'Error:',
      'network_error': 'Network error:',

      // === NEW KEYS FOR PAYMENT DIALOG ===
      'choose_sub_type': 'Select subscription type:',
      'sub_single': 'Single Subscription',
      'sub_team': 'Team Subscription',
      'sub_gift': 'Gift for Friends',
      'gift_friends': 'Gift for Friends',
      'add_one_friend_error': 'Add at least one friend',
      'server_error': 'Server Error',
      'processing': 'Processing request...',
      'link_open_error': 'Could not open link',

      // === NEW KEYS FOR LIMITS ===
      'limit_reached': 'Limit Reached',
      'limit_join_desc':
          'In the free version, you can save only 1 joined board. Get PRO for unlimited access.',
      'limit_host_desc':
          'In the free version, you can create only 1 hosting board. Get PRO for unlimited access.',
      'get_boardly_plus': 'Get BOARDLY+',
      'unlock_features': 'Unlock all features',
      // Main Menu
      'my_boards': 'My Boards',
      'hosting': 'Hosting',
      'joined': 'Joined',
      'boards': 'boards',
      'weight': 'Weight',
      'sent': 'Sent',
      'received': 'Received',
      'select_dir': 'Select working directory',
      'change_dir': 'Change directory',
      'policy': 'Terms and Privacy Policy',
      'profile': 'Profile',
      'login': 'Login',
      'registration': 'Registration',
      'auth_reg': 'Registration',
      'auth_login': 'Login',
      'login_hint': 'Login/Register',

      // New Buttons & Share
      'share': 'Share',
      'connect': 'Connect',
      'share_board_title': 'Share Board',
      'copy_id_btn': 'Copy ID',
      'share_instruction':
          'Send this ID to other users so they can join your session. They need to enter this code in the "Joined" section to connect.',
      'board_id': 'Board ID',
      'share_id': 'Share ID',

      // Messages (Start Screen)
      'dir_set': 'Working directory set:',
      'name_changed': 'Username changed!',
      'special_thanks': 'Special Thanks',
      'thanks_desc': 'This project was made possible by these amazing people:',
      'open_profile': 'Open profile',
      'link_error': 'Could not open link',
      'board_deleted_success': 'Board successfully deleted',
      'delete_error': 'Error deleting board',
      'dir_error': 'Error: Working directory not configured.',
      'id_copied': 'ID copied!',
      'welcome_user': 'Welcome,',
      'logout_confirm': 'Logged out successfully',

      // Profile & Auth
      'unknown': 'Unknown',
      'username': 'Username',
      'public_id_hint': 'Public ID',
      'change_password': 'Change Password',
      'logout': 'Logout',
      'reset_password': 'Password Reset',
      'your_email': 'Your Email',
      'email_code': 'Code from email',
      'new_password': 'New Password',
      'cancel': 'Cancel',
      'save': 'Save',
      'close': 'Close',
      'enter_email': 'Enter email',
      'update_pass': 'Update Password',
      'get_code': 'Get Code',
      'forgot_password': 'Forgot password?',
      'confirm_pass': 'Confirmation',
      'min_6_chars': 'Min. 6 characters',
      'pass_mismatch': 'Passwords do not match',
      'finish_reg': 'Complete Registration',
      'code_sent_email': 'Verification code sent to email',
      'change_name': 'Change name',
      'enter_new_name': 'Enter new name',
      'request_error': 'Request error',
      'password_changed_success': 'Password changed successfully!',
      'reset_error': 'Reset error',
      'unknown_error': 'Unknown error',
      'network_error': 'Network error:',
      'reg_success': 'Registration successful',
      'reg_error': 'Registration error:',
      'email': 'Email',
      'invalid_email': 'Invalid email',
      'password': 'Password',
      'confirm_code': 'Verification code',
      '6_digits': '6 digits',
      'login_btn': 'Login',
      'confirm': 'Confirm',
      'data_fetch_error': 'Data fetch error:',
      'error_prefix': 'Error:',

      // Board Screen
      'new_folder': 'New Folder',
      'create_folder': 'Create Folder',
      'folder_name': 'Folder Name',
      'pick_color': 'Pick Color:',
      'add_to_folder': 'Add to folder:',
      'objects': 'objects',
      'files_count': 'file(s)',
      'create_file': 'Create File',
      'file_name': 'File Name',
      'format': 'Format',
      'new_file_default': 'New File',
      'create_file_error': 'File creation error:',
      'blocked_ids': 'Blocked IDs',
      'blacklist_empty': 'Blacklist is empty',
      'unblock': 'Unblock',
      'file_exists': 'File already exists',
      'add_again_q': 'is already on the board. Add again?',
      'pick_files_error': 'Failed to pick files:',
      'open': 'Open',
      'remove_from_folder': 'Remove from folder',
      'add_tag': 'Add tag',
      'remove_from_board': 'Remove from board',
      'delete_file': 'Delete file',
      'tags_for': 'Tag(s) for',
      'enter_new_tag': 'Enter new tag',
      'existing_tags': 'Existing tags:',
      'notes': 'Notes',
      'enter_note_hint': 'Enter note...',
      'delete_arrow': 'Delete arrow',
      'arrow_settings': 'Arrow Settings',
      'line_width': 'Line thickness:',
      'color': 'Color:',
      'preview': 'Preview:',
      'files_list': 'Files List',
      'tags': 'Tags',
      'folders': 'Folders',
      'users': 'Users',
      'arrow_mode_hint': 'LMB: Arrow mode | RMB: Settings',
      'upload_file': 'Upload File',
      'search_hint': 'Search',
      'no_files_found': 'No files found',
      'no_tags_found': 'No tags found',
      'no_folders_found': 'No folders found',
      'no_active_users': 'No active users',
      'blacklist': 'Blacklist',
      'disconnect': 'Disconnect',
      'block': 'Block',
      'management': 'Management',
      'drop_files': 'Drop files here',
      'file_not_found': 'File not found:',
      'open_error': 'Open error:',

      // Shared
      'delete_q': 'Delete?',
      'delete_board_q': 'Delete board?',
      'no': 'No',
      'yes': 'Yes',
      'board_deleted': 'Board deleted',
      'create': 'Create',
      'no_boards': 'No boards found',
      'load_error': 'Failed to load',
      'title_for_self': 'Title (for yourself)',
      'board_id': 'Board ID',
      'join': 'Join',
      'add': 'Add',
      'delete_from_list_q': 'Delete from list?',
      'no_joined_boards': 'No joined boards',
      'guest': 'Guest',
      'no_local_boards': 'No local boards',
      'create_new_board': 'Create new board',
      'board_name_hint': 'e.g. "My Project"',
      'board_name': 'Board name',
      'create_board_error': 'Board creation error:',
      'board_removed': 'Board deleted',
      'new_board': 'New board',

      // Policy
      'policy_title': 'Terms & Policy',
      'decline': 'Decline',
      'agree': 'I Agree',
      'loading': 'Loading...',
      'policy_load_error': 'Error loading policy text. Contact support.',

      'arrow_settings_title': 'Arrow Settings',
      'arrow_thickness': 'Line thickness:',
      'arrow_color': 'Color:',
      'preview_label': 'Preview:',
      'pro_title': 'Boardly+',
      'pro_desc': 'Get access to advanced features for yourself and friends.',
      'add_friend_label': 'Add friend (Public ID):',
      'enter_id_hint': 'Enter ID...',
      'total_accounts': 'Total accounts:',
      'buy_pro': 'Buy Boardly+',
      'pro_redirect': 'Redirecting to payment...',
      'pro_active': 'Boardly+',
      'pro_active_desc': 'All features unlocked',
      'pro_badge': 'Boardly+',
      'accounts_count': 'accounts',

      'session_full_host':
          'Participant limit reached. Upgrade to Boardly+ for more.',

      'session_full_guest':
          'Session is full. The host has reached the connection limit.',

      'session_full_title': 'Access Denied',

      'about_title': 'About App',
      'app_description':
          'Short app description (2-4 lines). E.g., This is a real-time collaboration tool tailored for...',

      'features_title': 'Key Features',
      'feature_1': 'Real-time synchronization',
      'feature_2': 'Multi-format file support',
      'feature_3': 'Secure connection',

      'security_title': 'Security & Sync',
      'security_desc': 'Brief explanation of encryption or P2P connection...',

      'team_title': 'Development Team',
      'developer': 'Developer',
      'tester': 'QA / Tester',
      'designer': 'UI/UX & Logo',

      'contacts_title': 'Contacts & Info',
      'website': 'Website',
      'feedback': 'Contact Us',

      'resources_title': 'Resources & Credits',
      'resources_desc': 'Graphics and icons provided by:',

      'app_version': 'App Version',
      'build_number': 'Build',
    },
  };

  static String t(String key) {
    return _values[appLocale.value.languageCode]?[key] ?? key;
  }
}
